// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulator/simulator.proto

package simulator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DevicesCreationRequest struct {
	TenantId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Model                *wrappers.StringValue `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	NumberDevices        int32                 `protobuf:"varint,3,opt,name=number_devices,json=numberDevices,proto3" json:"number_devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DevicesCreationRequest) Reset()         { *m = DevicesCreationRequest{} }
func (m *DevicesCreationRequest) String() string { return proto.CompactTextString(m) }
func (*DevicesCreationRequest) ProtoMessage()    {}
func (*DevicesCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66faf123748dafc, []int{0}
}

func (m *DevicesCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesCreationRequest.Unmarshal(m, b)
}
func (m *DevicesCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesCreationRequest.Marshal(b, m, deterministic)
}
func (m *DevicesCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesCreationRequest.Merge(m, src)
}
func (m *DevicesCreationRequest) XXX_Size() int {
	return xxx_messageInfo_DevicesCreationRequest.Size(m)
}
func (m *DevicesCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesCreationRequest proto.InternalMessageInfo

func (m *DevicesCreationRequest) GetTenantId() *wrappers.StringValue {
	if m != nil {
		return m.TenantId
	}
	return nil
}

func (m *DevicesCreationRequest) GetModel() *wrappers.StringValue {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *DevicesCreationRequest) GetNumberDevices() int32 {
	if m != nil {
		return m.NumberDevices
	}
	return 0
}

type DevicesDataSimulationRequest struct {
	TenantId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SerialNumber         *wrappers.StringValue `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	EventType            *wrappers.StringValue `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	NumberEvents         int32                 `protobuf:"varint,4,opt,name=number_events,json=numberEvents,proto3" json:"number_events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DevicesDataSimulationRequest) Reset()         { *m = DevicesDataSimulationRequest{} }
func (m *DevicesDataSimulationRequest) String() string { return proto.CompactTextString(m) }
func (*DevicesDataSimulationRequest) ProtoMessage()    {}
func (*DevicesDataSimulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66faf123748dafc, []int{1}
}

func (m *DevicesDataSimulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesDataSimulationRequest.Unmarshal(m, b)
}
func (m *DevicesDataSimulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesDataSimulationRequest.Marshal(b, m, deterministic)
}
func (m *DevicesDataSimulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesDataSimulationRequest.Merge(m, src)
}
func (m *DevicesDataSimulationRequest) XXX_Size() int {
	return xxx_messageInfo_DevicesDataSimulationRequest.Size(m)
}
func (m *DevicesDataSimulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesDataSimulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesDataSimulationRequest proto.InternalMessageInfo

func (m *DevicesDataSimulationRequest) GetTenantId() *wrappers.StringValue {
	if m != nil {
		return m.TenantId
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetSerialNumber() *wrappers.StringValue {
	if m != nil {
		return m.SerialNumber
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetEventType() *wrappers.StringValue {
	if m != nil {
		return m.EventType
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetNumberEvents() int32 {
	if m != nil {
		return m.NumberEvents
	}
	return 0
}

type DeviceSimulationResponse struct {
	SimulationSucced     *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=simulation_succed,json=simulationSucced,proto3" json:"simulation_succed,omitempty"`
	DetailedMessage      *wrappers.StringValue `protobuf:"bytes,2,opt,name=detailed_message,json=detailedMessage,proto3" json:"detailed_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeviceSimulationResponse) Reset()         { *m = DeviceSimulationResponse{} }
func (m *DeviceSimulationResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceSimulationResponse) ProtoMessage()    {}
func (*DeviceSimulationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66faf123748dafc, []int{2}
}

func (m *DeviceSimulationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSimulationResponse.Unmarshal(m, b)
}
func (m *DeviceSimulationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSimulationResponse.Marshal(b, m, deterministic)
}
func (m *DeviceSimulationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSimulationResponse.Merge(m, src)
}
func (m *DeviceSimulationResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceSimulationResponse.Size(m)
}
func (m *DeviceSimulationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSimulationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSimulationResponse proto.InternalMessageInfo

func (m *DeviceSimulationResponse) GetSimulationSucced() *wrappers.BoolValue {
	if m != nil {
		return m.SimulationSucced
	}
	return nil
}

func (m *DeviceSimulationResponse) GetDetailedMessage() *wrappers.StringValue {
	if m != nil {
		return m.DetailedMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*DevicesCreationRequest)(nil), "simulator.DevicesCreationRequest")
	proto.RegisterType((*DevicesDataSimulationRequest)(nil), "simulator.DevicesDataSimulationRequest")
	proto.RegisterType((*DeviceSimulationResponse)(nil), "simulator.DeviceSimulationResponse")
}

func init() { proto.RegisterFile("simulator/simulator.proto", fileDescriptor_d66faf123748dafc) }

var fileDescriptor_d66faf123748dafc = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x8b, 0xdb, 0x30,
	0x14, 0xac, 0xdb, 0xa6, 0x34, 0x2f, 0x49, 0x9b, 0x0a, 0x5a, 0xdc, 0x10, 0x4a, 0xea, 0x50, 0x9a,
	0x93, 0x03, 0xe9, 0xa9, 0xf4, 0xd4, 0x34, 0x25, 0xf4, 0xd0, 0x1e, 0xe2, 0xd0, 0xc3, 0x5e, 0x8c,
	0x1c, 0xbd, 0x35, 0x02, 0x5b, 0xf2, 0x4a, 0x72, 0x42, 0xfe, 0xd3, 0xb2, 0x7f, 0x66, 0xff, 0xcf,
	0xb2, 0xac, 0x94, 0x8f, 0x5d, 0x1c, 0x58, 0x1f, 0xf6, 0x26, 0xc6, 0x33, 0x4f, 0xf3, 0xc6, 0x23,
	0xf8, 0xa8, 0x79, 0x5e, 0x66, 0xd4, 0x48, 0x35, 0x3e, 0x9c, 0xc2, 0x42, 0x49, 0x23, 0x49, 0xf3,
	0x00, 0xf4, 0x3e, 0xa5, 0x52, 0xa6, 0x19, 0x8e, 0xed, 0x87, 0xa4, 0x3c, 0x1f, 0x6f, 0x14, 0x2d,
	0x0a, 0x54, 0xda, 0x51, 0x83, 0x2b, 0x0f, 0x3e, 0xcc, 0x70, 0xcd, 0x57, 0xa8, 0x7f, 0x29, 0xa4,
	0x86, 0x4b, 0xb1, 0xc0, 0x8b, 0x12, 0xb5, 0x21, 0xdf, 0xa1, 0x69, 0x50, 0x50, 0x61, 0x62, 0xce,
	0x7c, 0x6f, 0xe0, 0x8d, 0x5a, 0x93, 0x7e, 0xe8, 0xc6, 0x85, 0xfb, 0x71, 0x61, 0x64, 0x14, 0x17,
	0xe9, 0x7f, 0x9a, 0x95, 0xb8, 0x78, 0xed, 0xe8, 0x7f, 0x18, 0x99, 0x40, 0x23, 0x97, 0x0c, 0x33,
	0xff, 0x79, 0x0d, 0x99, 0xa3, 0x92, 0x2f, 0xf0, 0x46, 0x94, 0x79, 0x82, 0x2a, 0x66, 0xce, 0x8f,
	0xff, 0x62, 0xe0, 0x8d, 0x1a, 0x8b, 0x8e, 0x43, 0x77, 0x26, 0x83, 0x1b, 0x0f, 0xfa, 0xbb, 0xf3,
	0x8c, 0x1a, 0x1a, 0xb9, 0x4d, 0x9f, 0xc6, 0xf6, 0x4f, 0xe8, 0x68, 0x54, 0x9c, 0x66, 0xb1, 0xbb,
	0xb3, 0x96, 0xfd, 0xb6, 0x93, 0xfc, 0xb3, 0x0a, 0xf2, 0x03, 0x00, 0xd7, 0x28, 0x4c, 0x6c, 0xb6,
	0x05, 0xda, 0x0d, 0x1e, 0xd3, 0x37, 0x2d, 0x7f, 0xb9, 0x2d, 0x90, 0x0c, 0x61, 0xb7, 0x6c, 0x6c,
	0x31, 0xed, 0xbf, 0xb4, 0x09, 0xb4, 0x1d, 0xf8, 0xdb, 0x62, 0xc1, 0xa5, 0x07, 0xbe, 0x0b, 0xe0,
	0xfe, 0xee, 0xba, 0x90, 0x42, 0x23, 0x99, 0xc3, 0x3b, 0x7d, 0x40, 0x63, 0x5d, 0xae, 0x56, 0xb8,
	0x0f, 0xa1, 0x57, 0x71, 0x31, 0x95, 0x32, 0x73, 0x1e, 0xba, 0x47, 0x51, 0x64, 0x35, 0x64, 0x0e,
	0x5d, 0x86, 0x86, 0xf2, 0x0c, 0x59, 0x9c, 0xa3, 0xd6, 0x34, 0xc5, 0x5a, 0x69, 0xbc, 0xdd, 0xab,
	0xfe, 0x3a, 0xd1, 0xe4, 0xda, 0x03, 0x70, 0x3f, 0x74, 0xb9, 0xe1, 0x82, 0x50, 0x78, 0x6f, 0x7b,
	0x86, 0x0f, 0x56, 0x40, 0x46, 0x3e, 0x87, 0xc7, 0x16, 0x9f, 0x2e, 0x64, 0x6f, 0x58, 0xa1, 0x54,
	0x13, 0x08, 0x9e, 0x91, 0x04, 0xba, 0x11, 0x0a, 0x76, 0xd7, 0x8e, 0xa5, 0x74, 0x3c, 0xf2, 0xb5,
	0x3a, 0xfd, 0x64, 0x7b, 0x6a, 0xde, 0x31, 0x6d, 0x9d, 0x1d, 0xdf, 0x58, 0xf2, 0xca, 0x26, 0xf1,
	0xed, 0x36, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x9e, 0x6c, 0xaf, 0x92, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceTwinClient is the client API for DeviceTwin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceTwinClient interface {
	CreateDeviceSimulated(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error)
	SendDataToDevice(ctx context.Context, in *DevicesDataSimulationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error)
}

type deviceTwinClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceTwinClient(cc grpc.ClientConnInterface) DeviceTwinClient {
	return &deviceTwinClient{cc}
}

func (c *deviceTwinClient) CreateDeviceSimulated(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error) {
	out := new(DeviceSimulationResponse)
	err := c.cc.Invoke(ctx, "/simulator.deviceTwin/CreateDeviceSimulated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTwinClient) SendDataToDevice(ctx context.Context, in *DevicesDataSimulationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error) {
	out := new(DeviceSimulationResponse)
	err := c.cc.Invoke(ctx, "/simulator.deviceTwin/SendDataToDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceTwinServer is the server API for DeviceTwin service.
type DeviceTwinServer interface {
	CreateDeviceSimulated(context.Context, *DevicesCreationRequest) (*DeviceSimulationResponse, error)
	SendDataToDevice(context.Context, *DevicesDataSimulationRequest) (*DeviceSimulationResponse, error)
}

// UnimplementedDeviceTwinServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceTwinServer struct {
}

func (*UnimplementedDeviceTwinServer) CreateDeviceSimulated(ctx context.Context, req *DevicesCreationRequest) (*DeviceSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceSimulated not implemented")
}
func (*UnimplementedDeviceTwinServer) SendDataToDevice(ctx context.Context, req *DevicesDataSimulationRequest) (*DeviceSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataToDevice not implemented")
}

func RegisterDeviceTwinServer(s *grpc.Server, srv DeviceTwinServer) {
	s.RegisterService(&_DeviceTwin_serviceDesc, srv)
}

func _DeviceTwin_CreateDeviceSimulated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTwinServer).CreateDeviceSimulated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simulator.deviceTwin/CreateDeviceSimulated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTwinServer).CreateDeviceSimulated(ctx, req.(*DevicesCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTwin_SendDataToDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesDataSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTwinServer).SendDataToDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simulator.deviceTwin/SendDataToDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTwinServer).SendDataToDevice(ctx, req.(*DevicesDataSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceTwin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simulator.deviceTwin",
	HandlerType: (*DeviceTwinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeviceSimulated",
			Handler:    _DeviceTwin_CreateDeviceSimulated_Handler,
		},
		{
			MethodName: "SendDataToDevice",
			Handler:    _DeviceTwin_SendDataToDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulator/simulator.proto",
}
