// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulator.proto

package simulator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DevicesCreationRequest struct {
	TenantId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Model                *wrappers.StringValue `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	NumberDevices        *wrappers.StringValue `protobuf:"bytes,3,opt,name=number_devices,json=numberDevices,proto3" json:"number_devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DevicesCreationRequest) Reset()         { *m = DevicesCreationRequest{} }
func (m *DevicesCreationRequest) String() string { return proto.CompactTextString(m) }
func (*DevicesCreationRequest) ProtoMessage()    {}
func (*DevicesCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16714ce4f39d8016, []int{0}
}

func (m *DevicesCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesCreationRequest.Unmarshal(m, b)
}
func (m *DevicesCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesCreationRequest.Marshal(b, m, deterministic)
}
func (m *DevicesCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesCreationRequest.Merge(m, src)
}
func (m *DevicesCreationRequest) XXX_Size() int {
	return xxx_messageInfo_DevicesCreationRequest.Size(m)
}
func (m *DevicesCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesCreationRequest proto.InternalMessageInfo

func (m *DevicesCreationRequest) GetTenantId() *wrappers.StringValue {
	if m != nil {
		return m.TenantId
	}
	return nil
}

func (m *DevicesCreationRequest) GetModel() *wrappers.StringValue {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *DevicesCreationRequest) GetNumberDevices() *wrappers.StringValue {
	if m != nil {
		return m.NumberDevices
	}
	return nil
}

type DevicesDataSimulationRequest struct {
	TenantId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SerialNumber         *wrappers.StringValue `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	EventType            *wrappers.StringValue `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	NumberDevices        *wrappers.StringValue `protobuf:"bytes,4,opt,name=number_devices,json=numberDevices,proto3" json:"number_devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DevicesDataSimulationRequest) Reset()         { *m = DevicesDataSimulationRequest{} }
func (m *DevicesDataSimulationRequest) String() string { return proto.CompactTextString(m) }
func (*DevicesDataSimulationRequest) ProtoMessage()    {}
func (*DevicesDataSimulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16714ce4f39d8016, []int{1}
}

func (m *DevicesDataSimulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesDataSimulationRequest.Unmarshal(m, b)
}
func (m *DevicesDataSimulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesDataSimulationRequest.Marshal(b, m, deterministic)
}
func (m *DevicesDataSimulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesDataSimulationRequest.Merge(m, src)
}
func (m *DevicesDataSimulationRequest) XXX_Size() int {
	return xxx_messageInfo_DevicesDataSimulationRequest.Size(m)
}
func (m *DevicesDataSimulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesDataSimulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesDataSimulationRequest proto.InternalMessageInfo

func (m *DevicesDataSimulationRequest) GetTenantId() *wrappers.StringValue {
	if m != nil {
		return m.TenantId
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetSerialNumber() *wrappers.StringValue {
	if m != nil {
		return m.SerialNumber
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetEventType() *wrappers.StringValue {
	if m != nil {
		return m.EventType
	}
	return nil
}

func (m *DevicesDataSimulationRequest) GetNumberDevices() *wrappers.StringValue {
	if m != nil {
		return m.NumberDevices
	}
	return nil
}

type DeviceSimulationResponse struct {
	SimulationSucced     *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=simulation_succed,json=simulationSucced,proto3" json:"simulation_succed,omitempty"`
	DetailedMessage      *wrappers.StringValue `protobuf:"bytes,2,opt,name=detailed_message,json=detailedMessage,proto3" json:"detailed_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeviceSimulationResponse) Reset()         { *m = DeviceSimulationResponse{} }
func (m *DeviceSimulationResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceSimulationResponse) ProtoMessage()    {}
func (*DeviceSimulationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16714ce4f39d8016, []int{2}
}

func (m *DeviceSimulationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSimulationResponse.Unmarshal(m, b)
}
func (m *DeviceSimulationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSimulationResponse.Marshal(b, m, deterministic)
}
func (m *DeviceSimulationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSimulationResponse.Merge(m, src)
}
func (m *DeviceSimulationResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceSimulationResponse.Size(m)
}
func (m *DeviceSimulationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSimulationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSimulationResponse proto.InternalMessageInfo

func (m *DeviceSimulationResponse) GetSimulationSucced() *wrappers.BoolValue {
	if m != nil {
		return m.SimulationSucced
	}
	return nil
}

func (m *DeviceSimulationResponse) GetDetailedMessage() *wrappers.StringValue {
	if m != nil {
		return m.DetailedMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*DevicesCreationRequest)(nil), "DevicesCreationRequest")
	proto.RegisterType((*DevicesDataSimulationRequest)(nil), "DevicesDataSimulationRequest")
	proto.RegisterType((*DeviceSimulationResponse)(nil), "DeviceSimulationResponse")
}

func init() { proto.RegisterFile("simulator.proto", fileDescriptor_16714ce4f39d8016) }

var fileDescriptor_16714ce4f39d8016 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xf2, 0xaa, 0x91, 0x51, 0x04, 0x36, 0x51, 0x2b, 0x21, 0xc6, 0x70, 0xf2, 0x54,
	0x12, 0x3c, 0x19, 0x4f, 0x0a, 0x09, 0x7a, 0xc0, 0x03, 0x25, 0x5e, 0x9b, 0x85, 0x1d, 0x9b, 0x4d,
	0xb6, 0xbb, 0x75, 0x77, 0x0b, 0xe1, 0xcb, 0xf8, 0x09, 0xf8, 0x28, 0x7e, 0x28, 0x43, 0x17, 0xfc,
	0x13, 0x31, 0xa9, 0xc6, 0xdb, 0xb4, 0xfb, 0xfc, 0x66, 0xe6, 0x79, 0x32, 0x50, 0x35, 0x3c, 0xc9,
	0x04, 0xb5, 0x4a, 0x07, 0xa9, 0x56, 0x56, 0x35, 0x4e, 0x63, 0xa5, 0x62, 0x81, 0xed, 0xfc, 0x6b,
	0x9c, 0x3d, 0xb6, 0x67, 0x9a, 0xa6, 0x29, 0x6a, 0xe3, 0xde, 0x5b, 0x2f, 0x1e, 0x1c, 0xf5, 0x70,
	0xca, 0x27, 0x68, 0xba, 0x1a, 0xa9, 0xe5, 0x4a, 0x0e, 0xf1, 0x29, 0x43, 0x63, 0xc9, 0x25, 0x94,
	0x2d, 0x4a, 0x2a, 0x6d, 0xc4, 0x99, 0xef, 0x9d, 0x79, 0xe7, 0x7b, 0x9d, 0x66, 0xe0, 0xda, 0x05,
	0xeb, 0x76, 0x41, 0x68, 0x35, 0x97, 0xf1, 0x03, 0x15, 0x19, 0x0e, 0x77, 0x9d, 0xfc, 0x8e, 0x91,
	0x0e, 0x6c, 0x27, 0x8a, 0xa1, 0xf0, 0x4b, 0x05, 0x30, 0x27, 0x25, 0x5d, 0x38, 0x90, 0x59, 0x32,
	0x46, 0x1d, 0x31, 0xb7, 0x8f, 0xff, 0xbf, 0x00, 0x5c, 0x71, 0xcc, 0xca, 0x42, 0xeb, 0xb9, 0x04,
	0xcd, 0x55, 0xdd, 0xa3, 0x96, 0x86, 0x2e, 0x8d, 0xbf, 0x31, 0x75, 0x0d, 0x15, 0x83, 0x9a, 0x53,
	0x11, 0xb9, 0x99, 0x85, 0xcc, 0xed, 0x3b, 0xe4, 0x3e, 0x27, 0xc8, 0x15, 0x00, 0x4e, 0x51, 0xda,
	0xc8, 0xce, 0x53, 0x2c, 0xe4, 0xaf, 0x9c, 0xeb, 0x47, 0xf3, 0x14, 0x37, 0x04, 0xb4, 0xf5, 0xf3,
	0x80, 0x16, 0x1e, 0xf8, 0xae, 0xfe, 0x98, 0x8d, 0x49, 0x95, 0x34, 0x48, 0xfa, 0x50, 0x37, 0x6f,
	0x7f, 0x23, 0x93, 0x4d, 0x26, 0xb8, 0x0e, 0xa9, 0xf1, 0x65, 0xc8, 0x8d, 0x52, 0xc2, 0x8d, 0xa8,
	0xbd, 0x43, 0x61, 0xce, 0x90, 0x3e, 0xd4, 0x18, 0x5a, 0xca, 0x05, 0xb2, 0x28, 0x41, 0x63, 0x68,
	0x8c, 0x85, 0xd2, 0xaa, 0xae, 0xa9, 0x81, 0x83, 0x3a, 0x0b, 0x0f, 0xea, 0x6e, 0xdd, 0xd1, 0x8c,
	0xcb, 0x10, 0xf5, 0xb2, 0x24, 0x03, 0x38, 0xcc, 0x8f, 0x15, 0x3f, 0x39, 0x41, 0x46, 0x8e, 0x83,
	0xcd, 0xb7, 0xdc, 0x38, 0x09, 0xbe, 0x33, 0xdd, 0xfa, 0x47, 0x6e, 0xa1, 0x16, 0xa2, 0x64, 0xcb,
	0x83, 0x19, 0x29, 0xa7, 0xfb, 0x5d, 0xa7, 0xf1, 0x4e, 0xee, 0xea, 0xe2, 0x35, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x88, 0x68, 0x41, 0x87, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeviceTwinServiceClient is the client API for DeviceTwinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceTwinServiceClient interface {
	CreateDeviceSimulated(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error)
	SendDataToDevice(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error)
}

type deviceTwinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceTwinServiceClient(cc grpc.ClientConnInterface) DeviceTwinServiceClient {
	return &deviceTwinServiceClient{cc}
}

func (c *deviceTwinServiceClient) CreateDeviceSimulated(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error) {
	out := new(DeviceSimulationResponse)
	err := c.cc.Invoke(ctx, "/DeviceTwinService/CreateDeviceSimulated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceTwinServiceClient) SendDataToDevice(ctx context.Context, in *DevicesCreationRequest, opts ...grpc.CallOption) (*DeviceSimulationResponse, error) {
	out := new(DeviceSimulationResponse)
	err := c.cc.Invoke(ctx, "/DeviceTwinService/SendDataToDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceTwinServiceServer is the server API for DeviceTwinService service.
type DeviceTwinServiceServer interface {
	CreateDeviceSimulated(context.Context, *DevicesCreationRequest) (*DeviceSimulationResponse, error)
	SendDataToDevice(context.Context, *DevicesCreationRequest) (*DeviceSimulationResponse, error)
}

// UnimplementedDeviceTwinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceTwinServiceServer struct {
}

func (*UnimplementedDeviceTwinServiceServer) CreateDeviceSimulated(ctx context.Context, req *DevicesCreationRequest) (*DeviceSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceSimulated not implemented")
}
func (*UnimplementedDeviceTwinServiceServer) SendDataToDevice(ctx context.Context, req *DevicesCreationRequest) (*DeviceSimulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDataToDevice not implemented")
}

func RegisterDeviceTwinServiceServer(s *grpc.Server, srv DeviceTwinServiceServer) {
	s.RegisterService(&_DeviceTwinService_serviceDesc, srv)
}

func _DeviceTwinService_CreateDeviceSimulated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTwinServiceServer).CreateDeviceSimulated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeviceTwinService/CreateDeviceSimulated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTwinServiceServer).CreateDeviceSimulated(ctx, req.(*DevicesCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceTwinService_SendDataToDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceTwinServiceServer).SendDataToDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeviceTwinService/SendDataToDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceTwinServiceServer).SendDataToDevice(ctx, req.(*DevicesCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceTwinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DeviceTwinService",
	HandlerType: (*DeviceTwinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeviceSimulated",
			Handler:    _DeviceTwinService_CreateDeviceSimulated_Handler,
		},
		{
			MethodName: "SendDataToDevice",
			Handler:    _DeviceTwinService_SendDataToDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulator.proto",
}
